# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{coderjoe-sc2ranks}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dennis Theisen", "Joe Bauser"]
  s.date = %q{2010-11-19}
  s.description = %q{A Ruby gem for accessing sc2ranks.com supporting fetching SC2 Base characters, team info, and mass base character fetch. This gem is a development fork of https://github.com/Soleone/sc2ranks}
  s.email = %q{coderjoe@coderjoe.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "fixtures/vcr_cassettes/README",
     "lib/sc2ranks.rb",
     "lib/sc2ranks/api.rb",
     "lib/sc2ranks/character.rb",
     "lib/sc2ranks/sc2ranks.rb",
     "test/helper.rb",
     "test/test_sc2ranks.rb"
  ]
  s.homepage = %q{https://github.com/coderjoe/sc2ranks/tree/coderjoe-sc2ranks.gem}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Ruby gem for accessing sc2ranks.com}
  s.test_files = [
    "test/test_sc2ranks.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_development_dependency(%q<contest>, [">= 0.1.2"])
      s.add_development_dependency(%q<vcr>, [">= 1.2.0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_dependency(%q<contest>, [">= 0.1.2"])
      s.add_dependency(%q<vcr>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
    s.add_dependency(%q<contest>, [">= 0.1.2"])
    s.add_dependency(%q<vcr>, [">= 1.2.0"])
  end
end

